name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test with coverage
      run: dotnet test --no-build --collect:"XPlat Code Coverage"
    - name: Publish test results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage
        path: $(System.DefaultWorkingDirectory)/TestResults
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./TestResults/*.xml
        flags: pull_request
        name: codecov-pull-request
